// ══════════════════════════════════════════════
// DATA
// ══════════════════════════════════════════════
const LANGS={fr:{name:'Français',flag:'🇫🇷',native:'Français'},en:{name:'Anglais',flag:'🇬🇧',native:'English'},es:{name:'Espagnol',flag:'🇪🇸',native:'Español'},de:{name:'Allemand',flag:'🇩🇪',native:'Deutsch'},cs:{name:'Tchèque',flag:'🇨🇿',native:'Čeština'}};
const LEVELS=[{id:'A1',label:'A1 — Débutant',desc:'Salutations, chiffres, couleurs'},{id:'A2',label:'A2 — Élémentaire',desc:'Famille, nourriture, maison'},{id:'B1',label:'B1 — Intermédiaire',desc:'Voyages, passé & futur'},{id:'B2',label:'B2 — Avancé',desc:'Actualité, idiomes'},{id:'C1',label:'C1 — Expert',desc:'Argumentation, registres'},{id:'C2',label:'C2 — Maîtrise',desc:'Littérature, humour'}];
const WD={hello:{fr:'Bonjour',en:'Hello',es:'Hola',de:'Hallo',cs:'Ahoj'},goodbye:{fr:'Au revoir',en:'Goodbye',es:'Adiós',de:'Auf Wiedersehen',cs:'Na shledanou'},thanks:{fr:'Merci',en:'Thank you',es:'Gracias',de:'Danke',cs:'Děkuji'},please:{fr:'S\'il vous plaît',en:'Please',es:'Por favor',de:'Bitte',cs:'Prosím'},yes:{fr:'Oui',en:'Yes',es:'Sí',de:'Ja',cs:'Ano'},no:{fr:'Non',en:'No',es:'No',de:'Nein',cs:'Ne'},sorry:{fr:'Pardon',en:'Sorry',es:'Lo siento',de:'Entschuldigung',cs:'Promiňte'},excuse:{fr:'Excusez-moi',en:'Excuse me',es:'Permiso',de:'Verzeihung',cs:'S dovolením'},one:{fr:'Un',en:'One',es:'Uno',de:'Eins',cs:'Jeden'},two:{fr:'Deux',en:'Two',es:'Dos',de:'Zwei',cs:'Dva'},three:{fr:'Trois',en:'Three',es:'Tres',de:'Drei',cs:'Tři'},four:{fr:'Quatre',en:'Four',es:'Cuatro',de:'Vier',cs:'Čtyři'},five:{fr:'Cinq',en:'Five',es:'Cinco',de:'Fünf',cs:'Pět'},ten:{fr:'Dix',en:'Ten',es:'Diez',de:'Zehn',cs:'Deset'},twenty:{fr:'Vingt',en:'Twenty',es:'Veinte',de:'Zwanzig',cs:'Dvacet'},hundred:{fr:'Cent',en:'Hundred',es:'Cien',de:'Hundert',cs:'Sto'},red:{fr:'Rouge',en:'Red',es:'Rojo',de:'Rot',cs:'Červená'},blue:{fr:'Bleu',en:'Blue',es:'Azul',de:'Blau',cs:'Modrá'},green:{fr:'Vert',en:'Green',es:'Verde',de:'Grün',cs:'Zelená'},yellow:{fr:'Jaune',en:'Yellow',es:'Amarillo',de:'Gelb',cs:'Žlutá'},black:{fr:'Noir',en:'Black',es:'Negro',de:'Schwarz',cs:'Černá'},white:{fr:'Blanc',en:'White',es:'Blanco',de:'Weiß',cs:'Bílá'},orange:{fr:'Orange',en:'Orange',es:'Naranja',de:'Orange',cs:'Oranžová'},pink:{fr:'Rose',en:'Pink',es:'Rosa',de:'Rosa',cs:'Růžová'},father:{fr:'Père',en:'Father',es:'Padre',de:'Vater',cs:'Otec'},mother:{fr:'Mère',en:'Mother',es:'Madre',de:'Mutter',cs:'Matka'},brother:{fr:'Frère',en:'Brother',es:'Hermano',de:'Bruder',cs:'Bratr'},sister:{fr:'Sœur',en:'Sister',es:'Hermana',de:'Schwester',cs:'Sestra'},grandfather:{fr:'Grand-père',en:'Grandfather',es:'Abuelo',de:'Großvater',cs:'Dědeček'},grandmother:{fr:'Grand-mère',en:'Grandmother',es:'Abuela',de:'Großmutter',cs:'Babička'},child:{fr:'Enfant',en:'Child',es:'Hijo',de:'Kind',cs:'Dítě'},cousin:{fr:'Cousin',en:'Cousin',es:'Primo',de:'Cousin',cs:'Bratranec'},bread:{fr:'Pain',en:'Bread',es:'Pan',de:'Brot',cs:'Chléb'},water:{fr:'Eau',en:'Water',es:'Agua',de:'Wasser',cs:'Voda'},coffee:{fr:'Café',en:'Coffee',es:'Café',de:'Kaffee',cs:'Káva'},wine:{fr:'Vin',en:'Wine',es:'Vino',de:'Wein',cs:'Víno'},meat:{fr:'Viande',en:'Meat',es:'Carne',de:'Fleisch',cs:'Maso'},fish:{fr:'Poisson',en:'Fish',es:'Pescado',de:'Fisch',cs:'Ryba'},fruit:{fr:'Fruit',en:'Fruit',es:'Fruta',de:'Frucht',cs:'Ovoce'},cheese:{fr:'Fromage',en:'Cheese',es:'Queso',de:'Käse',cs:'Sýr'},plane:{fr:'Avion',en:'Plane',es:'Avión',de:'Flugzeug',cs:'Letadlo'},train:{fr:'Train',en:'Train',es:'Tren',de:'Zug',cs:'Vlak'},hotel:{fr:'Hôtel',en:'Hotel',es:'Hotel',de:'Hotel',cs:'Hotel'},passport:{fr:'Passeport',en:'Passport',es:'Pasaporte',de:'Reisepass',cs:'Pas'},ticket:{fr:'Billet',en:'Ticket',es:'Billete',de:'Fahrkarte',cs:'Jízdenka'},suitcase:{fr:'Valise',en:'Suitcase',es:'Maleta',de:'Koffer',cs:'Kufr'},airport:{fr:'Aéroport',en:'Airport',es:'Aeropuerto',de:'Flughafen',cs:'Letiště'},reservation:{fr:'Réservation',en:'Booking',es:'Reserva',de:'Buchung',cs:'Rezervace'}};
const CHAPTERS={A1:[{id:'A1-1',title:{fr:'Salutations',en:'Greetings',es:'Saludos',de:'Begrüßung',cs:'Pozdravy'},subtitle:{fr:'Se présenter',en:'Meet people',es:'Presentarse',de:'Vorstellen',cs:'Predstavit se'},wids:['hello','goodbye','thanks','please','yes','no','sorry','excuse'],sents:{fr:['Je m appelle Marie','Comment tu t appelles','Enchante de te connaitre'],en:['My name is Tom','What is your name','Nice to meet you'],es:['Me llamo Carlos','Como te llamas','Encantado de conocerte'],de:['Ich heisse Klaus','Wie heisst du','Schon dich kennenzulernen'],cs:['Jmenuji se Marie','Jak se jmenujes','Rad te poznavam']}},{id:'A1-2',title:{fr:'Les Chiffres',en:'Numbers',es:'Números',de:'Zahlen',cs:'Čísla'},subtitle:{fr:'Compter de 1 à 100',en:'Count 1–100',es:'Contar 1–100',de:'Zählen 1–100',cs:'Počítat 1–100'},wids:['one','two','three','four','five','ten','twenty','hundred'],sents:{fr:['J ai vingt ans','Combien coute ce livre','Il est dix heures'],en:['I am twenty years old','How much is this book','It is ten o clock'],es:['Tengo veinte anos','Cuanto cuesta este libro','Son las diez'],de:['Ich bin zwanzig Jahre alt','Wie viel kostet dieses Buch','Es ist zehn Uhr'],cs:['Je mi dvacet let','Kolik stoji tato kniha','Je deset hodin']}},{id:'A1-3',title:{fr:'Les Couleurs',en:'Colours',es:'Colores',de:'Farben',cs:'Barvy'},subtitle:{fr:'Décrire avec les couleurs',en:'Describe with colours',es:'Describir con colores',de:'Mit Farben beschreiben',cs:'Popisovat barvami'},wids:['red','blue','green','yellow','black','white','orange','pink'],sents:{fr:['Le ciel est bleu','Ma voiture est rouge','J aime la couleur verte'],en:['The sky is blue','My car is red','I like the colour green'],es:['El cielo es azul','Mi coche es rojo','Me gusta el color verde'],de:['Der Himmel ist blau','Mein Auto ist rot','Ich mag die Farbe Grun'],cs:['Nebe je modre','Moje auto je cervene','Mam rad zelenou barvu']}}],A2:[{id:'A2-1',title:{fr:'La Famille',en:'Family',es:'La Familia',de:'Familie',cs:'Rodina'},subtitle:{fr:'Parler de sa famille',en:'Talk about your family',es:'Hablar de la familia',de:'Über Familie sprechen',cs:'Mluvit o rodině'},wids:['father','mother','brother','sister','grandfather','grandmother','child','cousin'],sents:{fr:['J ai deux freres et une soeur','Mon pere est medecin','Ma famille est grande'],en:['I have two brothers and a sister','My father is a doctor','My family is big'],es:['Tengo dos hermanos y una hermana','Mi padre es medico','Mi familia es grande'],de:['Ich habe zwei Bruder und eine Schwester','Mein Vater ist Arzt','Meine Familie ist gross'],cs:['Mam dva bratry a sestru','Muj otec je lekar','Moje rodina je velka']}},{id:'A2-2',title:{fr:'La Nourriture',en:'Food & Drink',es:'Comida',de:'Essen',cs:'Jídlo'},subtitle:{fr:'Commander de la nourriture',en:'Order food',es:'Pedir comida',de:'Essen bestellen',cs:'Objednat jídlo'},wids:['bread','water','coffee','wine','meat','fish','fruit','cheese'],sents:{fr:['Je voudrais un cafe','L addition s il vous plait','Le poisson est tres bon'],en:['I would like a coffee please','The bill please','The fish is very good'],es:['Quisiera un cafe por favor','La cuenta por favor','El pescado esta muy bueno'],de:['Ich hatte gerne einen Kaffee','Die Rechnung bitte','Der Fisch ist sehr gut'],cs:['Chtel bych kavu prosim','Ucet prosim','Ryba je velmi dobra']}}],B1:[{id:'B1-1',title:{fr:'Les Voyages',en:'Travel',es:'Viajes',de:'Reisen',cs:'Cestování'},subtitle:{fr:'Voyager et se déplacer',en:'Getting around',es:'Viajar',de:'Reisen',cs:'Cestovat'},wids:['plane','train','hotel','passport','ticket','suitcase','airport','reservation'],sents:{fr:['Mon vol est retarde de deux heures','J ai reserve une chambre pour trois nuits','Ou est l aeroport'],en:['My flight is delayed by two hours','I have booked a room for three nights','Where is the airport'],es:['Mi vuelo lleva dos horas de retraso','He reservado una habitacion por tres noches','Donde esta el aeropuerto'],de:['Mein Flug hat zwei Stunden Verspatung','Ich habe ein Zimmer fur drei Nachte gebucht','Wo ist der Flughafen'],cs:['Muj let ma dvouhodinove zpozdeni','Rezervoval jsem pokoj na tri noci','Kde je letiste']}}]};

// ASSETS (real-world inspired, always positive growth)
// INVESTOR LEVELS — based on totalInvested
const INVESTOR_LEVELS = [
  {level:1, title:'Débutant',     titleEn:'Beginner',   icon:'🌱', min:0,     max:100,   reward:0,   color:'#6b7280', unlocksAsset:null},
  {level:2, title:'Épargnant',    titleEn:'Saver',      icon:'💰', min:100,   max:400,   reward:25,  color:'#10b981', unlocksAsset:'house'},
  {level:3, title:'Investisseur', titleEn:'Investor',   icon:'📊', min:400,   max:1000,  reward:50,  color:'#06b6d4', unlocksAsset:'stock'},
  {level:4, title:'Trader',       titleEn:'Trader',     icon:'⚡', min:1000,  max:3000,  reward:100, color:'#7c3aed', unlocksAsset:'crypto'},
  {level:5, title:'Diversifié',   titleEn:'Diversified',icon:'🌍', min:3000,  max:8000,  reward:200, color:'#f59e0b', unlocksAsset:'etf'},
  {level:6, title:'Analyste',     titleEn:'Analyst',    icon:'🔬', min:8000,  max:20000, reward:400, color:'#ec4899', unlocksAsset:'bonds'},
  {level:7, title:'Gestionnaire', titleEn:'Manager',    icon:'🏦', min:20000, max:50000, reward:800, color:'#e11d48', unlocksAsset:'oil'},
  {level:8, title:'Tycoon',       titleEn:'Tycoon',     icon:'👑', min:50000, max:Infinity, reward:1500, color:'#d97706', unlocksAsset:'nasdaq'},
];

// EXPANDED ASSET_DEFS — 8 assets unlocked by investor level
const ASSET_DEFS=[
  {id:'gold',   name:'Or',           ticker:'GC=F',   cgId:null,      icon:'🥇', type:'Métal précieux',  class:'gold',   cost:50,  divRate:0.020, growthRate:0.0010, unlockLevel:1,
   desc:"L'or est l'actif refuge ultime. Depuis 5000 ans, il conserve sa valeur.",
   explain:"L'or physique protège contre l'inflation. Les banques centrales en détiennent des milliers de tonnes. Dividende : 2%/j car il génère un rendement de stockage virtuel.",
   realWhat:"Dans la réalité, l'or ne verse pas de dividende mais prend de la valeur en période de crise. GC=F est le contrat futures sur l'or du COMEX (Chicago)."},
  {id:'house',  name:'Immeuble',     ticker:'VNQ',    cgId:null,      icon:'🏢', type:'Immobilier',       class:'house',  cost:150, divRate:0.040, growthRate:0.0008, unlockLevel:2,
   desc:"L'immobilier génère des loyers réguliers. Actif physique, jamais à zéro.",
   explain:"VNQ est un REIT (Real Estate Investment Trust) : un fonds qui possède des centaines d'immeubles. Tu touches ta part des loyers chaque jour. Rendement élevé : 4%/j.",
   realWhat:"Les REITs sont obligés par loi de distribuer 90% de leurs bénéfices en dividendes. Le VNQ (Vanguard Real Estate ETF) inclut des centres commerciaux, bureaux, entrepôts."},
  {id:'stock',  name:'S&P 500',      ticker:'SPY',    cgId:null,      icon:'📈', type:'Actions USA',      class:'stock',  cost:80,  divRate:0.030, growthRate:0.0012, unlockLevel:3,
   desc:"Les 500 plus grandes entreprises américaines en un seul actif.",
   explain:"Le SPY est l'ETF le plus tradé au monde. Acheter 1 part = posséder un morceau d'Apple, Microsoft, Amazon, Tesla... Dividende : 3%/j basé sur leur rendement historique.",
   realWhat:"Historiquement, le S&P 500 rapporte ~10%/an. Il a survécu à toutes les crises. Warren Buffett recommande de l'acheter et de ne jamais le vendre."},
  {id:'crypto', name:'Bitcoin',      ticker:null,     cgId:'bitcoin', icon:'₿',  type:'Crypto-actif',     class:'crypto', cost:30,  divRate:0.015, growthRate:0.0020, unlockLevel:4,
   desc:"La première cryptomonnaie. Offre limitée à 21 millions de BTC.",
   explain:"Bitcoin est l'actif le plus volatile mais aussi le plus performant de la dernière décennie. Dividende virtuel 1.5%/j — faible car le potentiel de hausse est énorme.",
   realWhat:"BlackRock, Fidelity, et des dizaines de fonds gèrent maintenant des ETF Bitcoin. Son prix est corrélé au cycle de halvings (tous les ~4 ans)."},
  {id:'etf',    name:'ETF Monde',    ticker:'VT',     cgId:null,      icon:'🌐', type:'Actions mondiales', class:'etf',    cost:200, divRate:0.025, growthRate:0.0015, unlockLevel:5,
   desc:"3700 entreprises de 47 pays. La diversification ultime.",
   explain:"Le VT (Vanguard Total World) couvre 98% de la capitalisation boursière mondiale. USA, Europe, Asie, marchés émergents. Dividende modéré 2.5%/j — mais risque très faible.",
   realWhat:"Diversifier géographiquement réduit le risque spécifique à un pays. Si les USA chutent, l'Europe ou l'Asie peut compenser. Stratégie recommandée pour les investisseurs long terme."},
  {id:'bonds',  name:'Obligations',  ticker:'TLT',    cgId:null,      icon:'📜', type:'Dette souveraine',  class:'bonds',  cost:120, divRate:0.035, growthRate:0.0005, unlockLevel:6,
   desc:"Prêter de l'argent aux États-Unis en échange d'intérêts garantis.",
   explain:"TLT est un ETF d'obligations du Trésor US à 20 ans. Quand les taux baissent, les obligations montent. Dividende élevé 3.5%/j — revenu prévisible et stable.",
   realWhat:"Les obligations souveraines sont considérées comme 'sans risque' car un État ne fait jamais défaut (en théorie). Elles ont un rôle défensif dans un portefeuille."},
  {id:'oil',    name:'Pétrole',      ticker:'CL=F',   cgId:null,      icon:'🛢️', type:'Matière première',  class:'oil',    cost:90,  divRate:0.028, growthRate:0.0018, unlockLevel:7,
   desc:"L'or noir — moteur de l'économie mondiale.",
   explain:"CL=F est le crude oil WTI (West Texas Intermediate). Très volatile, mais les crises géopolitiques le font monter en flèche. Dividende 2.8%/j — bonne rentabilité cyclique.",
   realWhat:"L'OPEP+ contrôle la production mondiale. Quand ils réduisent les quotas, les prix explosent. Les énergies renouvelables créent une pression baissière à long terme."},
  {id:'nasdaq', name:'Nasdaq 100',   ticker:'QQQ',    cgId:null,      icon:'🚀', type:'Tech & Innovation',  class:'nasdaq', cost:250, divRate:0.022, growthRate:0.0025, unlockLevel:8,
   desc:"Les 100 plus grandes entreprises tech du monde. Le futur en action.",
   explain:"QQQ = Apple, Microsoft, Nvidia, Meta, Amazon, Google... Les géants de la tech. Croissance la plus rapide (+0.25%/j) mais dividende plus faible (2.2%/j).",
   realWhat:"Le Nasdaq 100 a multiplié par 7 en 10 ans. Très sensible aux taux d'intérêt et aux résultats trimestriels. Actif à fort potentiel mais volatil."},
];

// FINANCE ACADEMY — tutorial lessons
const FINANCE_LESSONS = [
  {id:'div101', title:'Les Dividendes', icon:'🌱', unlockLevel:1, reward:30, difficulty:'Débutant',
   intro:"Un dividende, c'est la part des bénéfices qu'une entreprise te reverse parce que tu possèdes une partie d'elle. Comme un loyer que tu touches sur ton investissement.",
   questions:[
     {q:"Qu'est-ce qu'un dividende ?", choices:["Une taxe sur les investissements","Un revenu versé par un actif à son propriétaire","Le prix d'achat d'une action","Un emprunt bancaire"], correct:1,
      explain:"Un dividende est un revenu passif — tu le reçois sans rien faire, juste parce que tu possèdes l'actif."},
     {q:"Si tu possèdes 100 pièces d'or avec un taux de dividende de 2%/jour, combien gagnes-tu par jour ?", choices:["0.2 pièce","2 pièces","20 pièces","200 pièces"], correct:1,
      explain:"100 × 2% = 2 pièces par jour. C'est l'intérêt simple sur ton investissement."},
     {q:"Pourquoi vaut-il mieux réinvestir ses dividendes ?", choices:["Ça fait baisser les impôts","Chaque dividende reinvesti génère lui-même des dividendes (intérêts composés)","C'est obligatoire par la loi","Pour éviter la volatilité"], correct:1,
      explain:"C'est l'intérêt composé : tes gains génèrent eux-mêmes des gains. Einstein l'appelait 'la 8e merveille du monde'."},
   ]},
  {id:'compound', title:"L'Intérêt Composé", icon:'📈', unlockLevel:1, reward:40, difficulty:'Débutant',
   intro:"L'intérêt composé, c'est quand tes gains génèrent eux-mêmes des gains. 100€ à 10%/an → 110€ la 1ère année, mais 121€ la 2ème (pas 120) car 10 génèrent aussi 10%.",
   questions:[
     {q:"Tu investis 100 pièces à 10%/an. Après 2 ans sans réinvestissement, tu as :", choices:["110 pièces","120 pièces","121 pièces","100 pièces"], correct:1,
      explain:"Sans réinvestissement = intérêt simple : 100 + 10 + 10 = 120. Avec composé ce serait 121."},
     {q:"Tu investis 100 pièces à 10%/an avec réinvestissement. Après 2 ans, tu as :", choices:["110 pièces","120 pièces","121 pièces","115 pièces"], correct:2,
      explain:"Année 1 : 100 × 1.10 = 110. Année 2 : 110 × 1.10 = 121. Les 10 gagnés en année 1 rapportent aussi 10%."},
     {q:"La règle des '72' permet de calculer :", choices:["Le montant des impôts","En combien d'années ton argent double","La meilleure heure pour trader","Le rendement d'un ETF"], correct:1,
      explain:"Règle des 72 : divise 72 par ton taux annuel. À 8%/an, ton argent double en 72/8 = 9 ans."},
     {q:"Pourquoi commencer à investir jeune est-il crucial ?", choices:["Les jeunes paient moins de frais","Plus d'années = plus d'intérêts composés = différence énorme","Les marchés montent toujours jeune","Ce n'est pas important"], correct:1,
      explain:"Investir 1000€ à 20 ans vs 40 ans à 7%/an : à 60 ans tu as 14 974€ vs 3 870€. Soit 4× plus juste en commençant 20 ans plus tôt."},
   ]},
  {id:'diversif', title:'La Diversification', icon:'🎯', unlockLevel:2, reward:60, difficulty:'Intermédiaire',
   intro:"'Ne mets pas tous tes œufs dans le même panier.' La diversification consiste à répartir ses investissements pour que la chute d'un actif ne ruine pas tout le portefeuille.",
   questions:[
     {q:"Tu as 1000 pièces. Laquelle de ces stratégies est la plus sûre ?", choices:["Tout dans Bitcoin","500 Bitcoin + 500 Or","250 Or + 250 Immo + 250 Actions + 250 Crypto","Tout dans l'Or"], correct:2,
      explain:"Répartir sur 4 actifs non-corrélés réduit le risque. Si le crypto chute de 50%, tu ne perds que 12.5% du total."},
     {q:"Qu'est-ce que la 'corrélation' entre actifs ?", choices:["Leur rendement annuel","À quel point ils montent/descendent ensemble","Leur prix actuel","Leur dividende"], correct:1,
      explain:"Des actifs corrélés montent et baissent ensemble. L'or et les actions sont souvent inversement corrélés — quand l'un baisse, l'autre monte. Parfait pour diversifier."},
     {q:"Le VT (ETF Monde) inclut des entreprises de combien de pays ?", choices:["5 pays","12 pays","47 pays","150 pays"], correct:2,
      explain:"Le VT couvre 47 pays et ~3700 entreprises. C'est la diversification maximale en un seul achat."},
   ]},
  {id:'riskreturn', title:'Risque & Rendement', icon:'⚖️', unlockLevel:3, reward:80, difficulty:'Intermédiaire',
   intro:"En finance, il n'y a pas de rendement élevé sans risque élevé. Le Bitcoin peut doubler en 1 an — mais aussi perdre 70%. Les obligations d'État sont moins rentables mais quasi-garanties.",
   questions:[
     {q:"Classe ces actifs du moins risqué au plus risqué :", choices:["Or → S&P500 → Obligations → Bitcoin","Obligations → Or → S&P500 → Bitcoin","Bitcoin → S&P500 → Or → Obligations","Tous ont le même risque"], correct:1,
      explain:"Les obligations souveraines sont quasi sans risque. L'or est stable. Le S&P500 est volatil mais diversifié. Bitcoin est le plus volatile de tous."},
     {q:"Tu veux un revenu stable et prévisible. Quel actif choisir ?", choices:["Bitcoin","Pétrole","Obligations d'État","Actions technologiques"], correct:2,
      explain:"Les obligations versent un coupon fixe garanti par l'État. Parfait pour un revenu sûr. Les autres actifs sont trop volatils pour cet objectif."},
     {q:"Qu'est-ce que la 'volatilité' ?", choices:["La vitesse à laquelle on peut vendre un actif","L'amplitude des variations de prix","Le rendement annualisé","Les frais de transaction"], correct:1,
      explain:"Un actif très volatile peut perdre ou gagner 20% en un jour. Haute volatilité = risque élevé ET potentiel de gain élevé. C'est le compromis fondamental en finance."},
     {q:"Qu'est-ce qu'un 'drawdown' ?", choices:["Une hausse soudaine","Un profit exceptionnel","La chute maximale depuis un sommet","Un type d'obligation"], correct:2,
      explain:"Le drawdown mesure la perte maximale depuis un pic. Le Bitcoin a eu des drawdowns de -80%. Le S&P 500 rarement plus de -50%."},
   ]},
  {id:'etfvsstocks', title:'ETF vs Actions', icon:'🔬', unlockLevel:4, reward:100, difficulty:'Avancé',
   intro:"Une action = un morceau d'une entreprise. Un ETF (Exchange Traded Fund) = un panier de centaines d'actions. L'ETF te donne la diversification en un seul achat.",
   questions:[
     {q:"Tu achètes une action Apple. Que se passe-t-il si Apple fait faillite ?", choices:["Tu perds 10%","Tu perds tout","L'État te rembourse","Tu reçois des obligations à la place"], correct:1,
      explain:"Une action peut valoir 0. Apple a peu de chances de faire faillite, mais Nokia, Kodak, Lehman Brothers l'ont fait. Concentration = risque maximal."},
     {q:"Quel est l'avantage principal d'un ETF sur une action individuelle ?", choices:["Il coûte moins cher","Il est garanti par l'État","Il diversifie automatiquement sur des centaines de valeurs","Il verse plus de dividendes"], correct:2,
      explain:"Acheter le SPY (S&P500 ETF), c'est posséder 500 entreprises en même temps. Si l'une coule, les 499 autres compensent."},
     {q:"Qu'est-ce que le ratio P/E (Price/Earnings) ?", choices:["Le prix divisé par les dividendes","Le prix de l'action divisé par le bénéfice annuel par action","La performance sur 5 ans","Les frais de gestion annuels"], correct:1,
      explain:"P/E = combien tu paies pour 1€ de bénéfice. P/E de 20 = tu paies 20€ pour 1€/an de bénéfice. Plus le P/E est bas, plus l'action est 'bon marché'."},
     {q:"Qu'est-ce qu'un 'expense ratio' (frais de gestion) d'un ETF ?", choices:["Le prix d'achat","Les frais annuels prélevés automatiquement sur la performance","La taxe de bourse","Les dividendes versés"], correct:1,
      explain:"Un ETF comme VT prend 0.07%/an. Un fonds actif peut prendre 1-2%/an. Sur 30 ans, la différence est massive à cause des intérêts composés."},
   ]},
  {id:'macro', title:'Macro-économie', icon:'🌍', unlockLevel:5, reward:150, difficulty:'Expert',
   intro:"Les marchés ne bougent pas au hasard. Les décisions des banques centrales, l'inflation, les taux d'intérêt, les cycles économiques — tout influence tes investissements.",
   questions:[
     {q:"Quand la Réserve Fédérale (Fed) hausse les taux d'intérêt, que se passe-t-il généralement ?", choices:["Les actions montent fortement","Les obligations montent, les actions baissent","Les actions et obligations montent ensemble","Rien ne change"], correct:1,
      explain:"Des taux élevés = l'argent coûte plus cher = les entreprises empruntent moins et investissent moins. Les obligations existantes (à taux fixe) perdent de la valeur en comparaison."},
     {q:"Qu'est-ce que l'inflation fait à ton argent en banque ?", choices:["Il gagne de la valeur","Il garde exactement la même valeur","Il perd de la valeur réelle si le rendement est inférieur à l'inflation","Il est garanti par l'État"], correct:2,
      explain:"Avec 3% d'inflation et 0.5% sur ton compte bancaire, tu perds -2.5% de pouvoir d'achat par an. C'est pourquoi investir est essentiel pour ne pas s'appauvrir."},
     {q:"Qu'est-ce qu'un 'marché haussier' (bull market) ?", choices:["Un marché qui monte d'au moins 20% depuis un creux","Un marché très volatil","Un marché où on achète des matières premières","Un marché fermé le lundi"], correct:0,
      explain:"Bull market = hausse soutenue de 20%+. Bear market = baisse de 20%+. Historiquement, les bull markets durent plus longtemps que les bear markets."},
     {q:"Le 'quantitative easing' (QE) consiste à :", choices:["Augmenter les impôts","La banque centrale crée de la monnaie pour acheter des actifs et stimuler l'économie","Vendre les réserves d'or d'un pays","Réduire les salaires"], correct:1,
      explain:"Le QE injecte de l'argent dans l'économie. Il a tendance à faire monter les marchés d'actions (mais peut créer de l'inflation). La Fed en a fait massivement en 2008 et 2020."},
   ]},
];



// SHOP ITEMS
const SHOP_ITEMS=[
  {id:'streak_shield',name:'Bouclier Série',icon:'🛡️',price:40,desc:'Protège ta série 1 fois si tu rates un jour',type:'consumable'},
  {id:'xp_boost',name:'Boost XP ×2',icon:'⚡',price:60,desc:'Double tes XP pendant 3 sessions',type:'consumable'},
  {id:'hint_pack',name:'Pack Indices',icon:'💡',price:25,desc:'5 indices gratuits pour les questions difficiles',type:'consumable'},
  {id:'avatar_gold',name:'Avatar Doré',icon:'👑',price:100,desc:'Badge exclusif sur ton profil',type:'cosmetic'},
  {id:'avatar_diamond',name:'Avatar Diamant',icon:'💎',price:200,desc:'Le badge le plus rare de LinguaQuest',type:'cosmetic'},
  {id:'bonus_coins',name:'Bonus Pièces',icon:'<span class="coin"></span>',price:0,desc:'Reçois 50 pièces bonus chaque semaine',type:'premium'},
];

// ══════════════════════════════════════════════
// UI STRINGS — full interface translations
// ══════════════════════════════════════════════
const UI_STRINGS = {
  fr:{
    // nav
    nav_learn:'Apprendre', nav_portfolio:'Portfolio', nav_shop:'Boutique', nav_profile:'Profil',
    // tagline / theme picker
    tagline:'Apprends. Investis. Maîtrise.',
    pick_theme:'Choisis ton thème',
    theme_dark:'🌙 Sombre', theme_light:'☀️ Clair', theme_claude:'🤖 Claude', theme_random:'🎲 Aléatoire',
    // auth
    tab_login:'Se connecter', tab_register:"S'inscrire",
    lbl_pass:'Mot de passe', lbl_reg_name:'Prénom / Pseudo', lbl_reg_email:'Email', lbl_reg_pass:'Mot de passe',
    btn_login:'Se connecter →', demo_link:'Connexion démo →',
    btn_register:'Créer mon compte 🚀',
    or_guest:'ou continuer sans compte',
    guest_btn:'👤 Continuer en invité', guest_warn:'La progression ne sera pas sauvegardée',
    ph_login_email:'ton@email.com', ph_login_pass:'••••••••',
    ph_reg_name:'Marie', ph_reg_email:'ton@email.com', ph_reg_pass:'Min. 6 caractères',
    // learn
    learn_tagline:'Choisis ta langue', i_speak:'🧑 Je parle', i_learn:'🎯 Je veux apprendre',
    btn_start:'Commencer →',
    // levels
    levels_sub:'Chaque niveau réutilise le vocabulaire précédent',
    // game select
    mix_badge:'🎲 Mode Mixte recommandé',
    gtype_mixed:'Mode Mixte', gdesc_mixed:"Tout mélangé — la meilleure façon d'apprendre",
    gtype_quiz:'Quiz Rapide', gdesc_quiz:'4 choix · Chrono · Style Kahoot',
    gtype_fill:'Compléter', gdesc_fill:'Tape le mot · Accents tolérés ✨',
    gtype_match:'Associer', gdesc_match:'Relie les mots et traductions',
    reward_mixed:'+30 pièces max', reward_quiz:'+15 pièces max', reward_fill:'+20 pièces max', reward_match:'+10 pièces max',
    // game
    ph_fill:'Écris ta réponse…',
    your_sent:'Ta phrase :', slot_placeholder:'Clique sur les mots…', words_avail:'Mots disponibles :',
    pairs:'paires', btn_check:'Vérifier ✓', btn_next:'Suivant →', btn_continue:'Continuer →',
    // results
    coins_won:'Pièces gagnées !', coins_hint:'Utilise-les pour investir dans le Portfolio',
    r_correct:'Correct', r_wrong:'Erreurs',
    btn_replay:'Rejouer 🔄', btn_r_chapters:'Chapitres', btn_r_invest:'$ Investir',
    // portfolio
    wealth_hero:'◈ Patrimoine total', liquid_coins:'Pièces liquides', div_day:'Dividendes / jour',
    invested:'Investi', div_avail:'Dividendes disponibles !',
    btn_collect:'Collecter',
    div_explain_title:'📖 Comment fonctionnent les dividendes ?',
    div_explain_body:"Dans la vraie vie, certains <strong>actifs</strong> (or, immobilier, actions) génèrent des revenus <strong>réguliers</strong> sans que tu doives les vendre. C'est ça un <span class=\"highlight\">dividende</span>.<br><br>Ici, chaque actif que tu achètes avec tes <span class=\"coin\"></span> pièces te rapporte automatiquement un pourcentage chaque jour. Comme dans la réalité, <strong>plus tu investis tôt, plus tu reçois</strong>. Les actifs <strong>n'ont pas de valeur négative</strong> — ils peuvent stagner ou croître, jamais disparaître.",
    target_title:'🎯 Simulateur d\'objectif',
    target_sub:"Fixe un objectif en pièces et vois combien de temps il faudra pour l'atteindre avec tes dividendes actuels.",
    target_obj:'Objectif :',
    tr_missing:'Il manque', tr_daily:'Dividendes / jour', tr_time:'Temps estimé', tr_progress:'Progression actuelle',
    tl_target:'Objectif', tl_now:'Maintenant',
    assets_title:'🏠 Actifs disponibles',
    // shop
    shop_title:'🛍 Boutique', shop_sub:'Dépense tes pièces pour des bonus et cosmétiques',
    shop_coins_lbl:'pièces disponibles',
    // profile
    ps_xp:'XP Total', ps_coins:'Pièces', ps_sessions:'Sessions',
    ps_streak:'🔥 Jours', ps_chapters:'Chapitres', ps_wealth:'💎 Patrimoine',
    appearance:'🎨 Apparence', lang_ui:"🌐 Langue de l'interface",
    btn_change_lang:'🌍 Changer de langue', btn_logout:'🚪 Se déconnecter',
    // qr modal
    qr_title:'📱 Partager ce chapitre', btn_qr_copy:'📋 Copier', btn_close:'Fermer',
    // lang modal
    langmodal_title:'Changer de langue', lm_speak:'Je parle :', lm_learn:"J'apprends :",
    btn_apply:'Appliquer', btn_cancel:'Annuler',
    // asset modal
    amod_market:'Prix marché réel', amod_position:'Ta position',
    amod_units:'Unités possédées', amod_value:'Valeur actuelle',
    amod_daily:'Dividendes / jour', amod_pv:'Plus-value',
    btn_buy:'Acheter', btn_sell:'Vendre',
    // joined
    joined:'Membre depuis ',
  },
  en:{
    nav_learn:'Learn', nav_portfolio:'Portfolio', nav_shop:'Shop', nav_profile:'Profile',
    tagline:'Learn. Invest. Master.',
    pick_theme:'Choose your theme',
    theme_dark:'🌙 Dark', theme_light:'☀️ Light', theme_claude:'🤖 Claude', theme_random:'🎲 Random',
    tab_login:'Log in', tab_register:'Sign up',
    lbl_pass:'Password', lbl_reg_name:'Name / Username', lbl_reg_email:'Email', lbl_reg_pass:'Password',
    btn_login:'Log in →', demo_link:'Demo login →',
    btn_register:'Create account 🚀',
    or_guest:'or continue without account',
    guest_btn:'👤 Continue as guest', guest_warn:'Progress will not be saved',
    ph_login_email:'your@email.com', ph_login_pass:'••••••••',
    ph_reg_name:'Alex', ph_reg_email:'your@email.com', ph_reg_pass:'Min. 6 characters',
    learn_tagline:'Choose your language', i_speak:'🧑 I speak', i_learn:'🎯 I want to learn',
    btn_start:'Start →',
    levels_sub:'Each level builds on previous vocabulary',
    mix_badge:'🎲 Mixed mode recommended',
    gtype_mixed:'Mixed Mode', gdesc_mixed:'All mixed — the best way to learn',
    gtype_quiz:'Quick Quiz', gdesc_quiz:'4 choices · Timer · Kahoot style',
    gtype_fill:'Fill in', gdesc_fill:'Type the word · Accents tolerated ✨',
    gtype_match:'Match', gdesc_match:'Link words and their translations',
    reward_mixed:'+30 coins max', reward_quiz:'+15 coins max', reward_fill:'+20 coins max', reward_match:'+10 coins max',
    ph_fill:'Write your answer…',
    your_sent:'Your sentence:', slot_placeholder:'Click on words…', words_avail:'Available words:',
    pairs:'pairs', btn_check:'Check ✓', btn_next:'Next →', btn_continue:'Continue →',
    coins_won:'Coins earned!', coins_hint:'Use them to invest in your Portfolio',
    r_correct:'Correct', r_wrong:'Wrong',
    btn_replay:'Play again 🔄', btn_r_chapters:'Chapters', btn_r_invest:'$ Invest',
    wealth_hero:'◈ Total wealth', liquid_coins:'Liquid coins', div_day:'Dividends / day',
    invested:'Invested', div_avail:'Dividends available!',
    btn_collect:'Collect',
    div_explain_title:'📖 How do dividends work?',
    div_explain_body:'In real life, some <strong>assets</strong> (gold, real estate, stocks) generate <strong>regular</strong> income without having to sell them. That is a <span class="highlight">dividend</span>.<br><br>Here, each asset you buy with your <span class="coin"></span> coins automatically earns you a percentage each day. As in real life, <strong>the earlier you invest, the more you earn</strong>. Assets <strong>never go negative</strong> — they may stagnate or grow, but never disappear.',
    target_title:'🎯 Goal simulator',
    target_sub:'Set a coin target and see how long it will take to reach it with your current dividends.',
    target_obj:'Target:',
    tr_missing:'Missing', tr_daily:'Dividends / day', tr_time:'Estimated time', tr_progress:'Current progress',
    tl_target:'Target', tl_now:'Now',
    assets_title:'🏠 Available assets',
    shop_title:'🛍 Shop', shop_sub:'Spend your coins on bonuses and cosmetics',
    shop_coins_lbl:'coins available',
    ps_xp:'Total XP', ps_coins:'Coins', ps_sessions:'Sessions',
    ps_streak:'🔥 Days', ps_chapters:'Chapters', ps_wealth:'💎 Wealth',
    appearance:'🎨 Appearance', lang_ui:'🌐 Interface language',
    btn_change_lang:'🌍 Change language', btn_logout:'🚪 Log out',
    qr_title:'📱 Share this chapter', btn_qr_copy:'📋 Copy', btn_close:'Close',
    langmodal_title:'Change language', lm_speak:'I speak:', lm_learn:'I want to learn:',
    btn_apply:'Apply', btn_cancel:'Cancel',
    amod_market:'Real market price', amod_position:'Your position',
    amod_units:'Units owned', amod_value:'Current value',
    amod_daily:'Dividends / day', amod_pv:'Capital gain',
    btn_buy:'Buy', btn_sell:'Sell',
    joined:'Member since ',
  },
  es:{
    nav_learn:'Aprender', nav_portfolio:'Portafolio', nav_shop:'Tienda', nav_profile:'Perfil',
    tagline:'Aprende. Invierte. Domina.',
    pick_theme:'Elige tu tema',
    theme_dark:'🌙 Oscuro', theme_light:'☀️ Claro', theme_claude:'🤖 Claude', theme_random:'🎲 Aleatorio',
    tab_login:'Iniciar sesión', tab_register:'Registrarse',
    lbl_pass:'Contraseña', lbl_reg_name:'Nombre / Usuario', lbl_reg_email:'Email', lbl_reg_pass:'Contraseña',
    btn_login:'Iniciar sesión →', demo_link:'Demo →',
    btn_register:'Crear cuenta 🚀',
    or_guest:'o continuar sin cuenta',
    guest_btn:'👤 Continuar como invitado', guest_warn:'El progreso no se guardará',
    ph_login_email:'tu@email.com', ph_login_pass:'••••••••',
    ph_reg_name:'Carlos', ph_reg_email:'tu@email.com', ph_reg_pass:'Mín. 6 caracteres',
    learn_tagline:'Elige tu idioma', i_speak:'🧑 Hablo', i_learn:'🎯 Quiero aprender',
    btn_start:'Empezar →',
    levels_sub:'Cada nivel reutiliza el vocabulario anterior',
    mix_badge:'🎲 Modo mixto recomendado',
    gtype_mixed:'Modo Mixto', gdesc_mixed:'Todo mezclado — la mejor forma de aprender',
    gtype_quiz:'Quiz Rápido', gdesc_quiz:'4 opciones · Cronómetro · Estilo Kahoot',
    gtype_fill:'Completar', gdesc_fill:'Escribe la palabra · Acentos tolerados ✨',
    gtype_match:'Asociar', gdesc_match:'Une las palabras con sus traducciones',
    reward_mixed:'+30 monedas máx', reward_quiz:'+15 monedas máx', reward_fill:'+20 monedas máx', reward_match:'+10 monedas máx',
    ph_fill:'Escribe tu respuesta…',
    your_sent:'Tu frase:', slot_placeholder:'Haz clic en las palabras…', words_avail:'Palabras disponibles:',
    pairs:'pares', btn_check:'Verificar ✓', btn_next:'Siguiente →', btn_continue:'Continuar →',
    coins_won:'¡Monedas ganadas!', coins_hint:'Úsalas para invertir en tu Portafolio',
    r_correct:'Correcto', r_wrong:'Errores',
    btn_replay:'Repetir 🔄', btn_r_chapters:'Capítulos', btn_r_invest:'$ Invertir',
    wealth_hero:'◈ Patrimonio total', liquid_coins:'Monedas líquidas', div_day:'Dividendos / día',
    invested:'Invertido', div_avail:'¡Dividendos disponibles!',
    btn_collect:'Cobrar',
    div_explain_title:'📖 ¿Cómo funcionan los dividendos?',
    div_explain_body:'En la vida real, ciertos <strong>activos</strong> (oro, inmuebles, acciones) generan ingresos <strong>regulares</strong> sin necesidad de venderlos. Eso es un <span class="highlight">dividendo</span>.<br><br>Aquí, cada activo que compras con tus <span class="coin"></span> monedas te genera automáticamente un porcentaje cada día. Como en la realidad, <strong>cuanto antes inviertas, más recibirás</strong>. Los activos <strong>nunca tienen valor negativo</strong>.',
    target_title:'🎯 Simulador de objetivo',
    target_sub:'Fija un objetivo en monedas y mira cuánto tiempo tardarás en alcanzarlo con tus dividendos actuales.',
    target_obj:'Objetivo:',
    tr_missing:'Faltan', tr_daily:'Dividendos / día', tr_time:'Tiempo estimado', tr_progress:'Progreso actual',
    tl_target:'Objetivo', tl_now:'Ahora',
    assets_title:'🏠 Activos disponibles',
    shop_title:'🛍 Tienda', shop_sub:'Gasta tus monedas en bonificaciones y cosméticos',
    shop_coins_lbl:'monedas disponibles',
    ps_xp:'XP Total', ps_coins:'Monedas', ps_sessions:'Sesiones',
    ps_streak:'🔥 Días', ps_chapters:'Capítulos', ps_wealth:'💎 Patrimonio',
    appearance:'🎨 Apariencia', lang_ui:'🌐 Idioma de la interfaz',
    btn_change_lang:'🌍 Cambiar idioma', btn_logout:'🚪 Cerrar sesión',
    qr_title:'📱 Compartir este capítulo', btn_qr_copy:'📋 Copiar', btn_close:'Cerrar',
    langmodal_title:'Cambiar idioma', lm_speak:'Hablo:', lm_learn:'Quiero aprender:',
    btn_apply:'Aplicar', btn_cancel:'Cancelar',
    amod_market:'Precio de mercado real', amod_position:'Tu posición',
    amod_units:'Unidades poseídas', amod_value:'Valor actual',
    amod_daily:'Dividendos / día', amod_pv:'Plusvalía',
    btn_buy:'Comprar', btn_sell:'Vender',
    joined:'Miembro desde ',
  },
  de:{
    nav_learn:'Lernen', nav_portfolio:'Portfolio', nav_shop:'Shop', nav_profile:'Profil',
    tagline:'Lernen. Investieren. Meistern.',
    pick_theme:'Wähle dein Thema',
    theme_dark:'🌙 Dunkel', theme_light:'☀️ Hell', theme_claude:'🤖 Claude', theme_random:'🎲 Zufällig',
    tab_login:'Anmelden', tab_register:'Registrieren',
    lbl_pass:'Passwort', lbl_reg_name:'Name / Benutzername', lbl_reg_email:'E-Mail', lbl_reg_pass:'Passwort',
    btn_login:'Anmelden →', demo_link:'Demo →',
    btn_register:'Konto erstellen 🚀',
    or_guest:'oder ohne Konto fortfahren',
    guest_btn:'👤 Als Gast fortfahren', guest_warn:'Fortschritt wird nicht gespeichert',
    ph_login_email:'deine@email.de', ph_login_pass:'••••••••',
    ph_reg_name:'Klaus', ph_reg_email:'deine@email.de', ph_reg_pass:'Mind. 6 Zeichen',
    learn_tagline:'Wähle deine Sprache', i_speak:'🧑 Ich spreche', i_learn:'🎯 Ich möchte lernen',
    btn_start:'Starten →',
    levels_sub:'Jede Stufe baut auf vorherigem Wortschatz auf',
    mix_badge:'🎲 Gemischter Modus empfohlen',
    gtype_mixed:'Gemischter Modus', gdesc_mixed:'Alles gemischt — die beste Lernmethode',
    gtype_quiz:'Schnell-Quiz', gdesc_quiz:'4 Optionen · Timer · Kahoot-Stil',
    gtype_fill:'Ergänzen', gdesc_fill:'Wort eingeben · Akzente toleriert ✨',
    gtype_match:'Zuordnen', gdesc_match:'Wörter mit Übersetzungen verbinden',
    reward_mixed:'+30 Münzen max', reward_quiz:'+15 Münzen max', reward_fill:'+20 Münzen max', reward_match:'+10 Münzen max',
    ph_fill:'Schreibe deine Antwort…',
    your_sent:'Dein Satz:', slot_placeholder:'Klicke auf Wörter…', words_avail:'Verfügbare Wörter:',
    pairs:'Paare', btn_check:'Prüfen ✓', btn_next:'Weiter →', btn_continue:'Fortfahren →',
    coins_won:'Münzen verdient!', coins_hint:'Nutze sie für Investitionen im Portfolio',
    r_correct:'Richtig', r_wrong:'Fehler',
    btn_replay:'Nochmal 🔄', btn_r_chapters:'Kapitel', btn_r_invest:'$ Investieren',
    wealth_hero:'◈ Gesamtvermögen', liquid_coins:'Flüssige Münzen', div_day:'Dividenden / Tag',
    invested:'Investiert', div_avail:'Dividenden verfügbar!',
    btn_collect:'Einsammeln',
    div_explain_title:'📖 Wie funktionieren Dividenden?',
    div_explain_body:'Im echten Leben erzeugen bestimmte <strong>Anlagen</strong> (Gold, Immobilien, Aktien) <strong>regelmäßige</strong> Einnahmen, ohne sie verkaufen zu müssen. Das ist eine <span class="highlight">Dividende</span>.<br><br>Hier bringt dir jede Anlage, die du mit deinen <span class="coin"></span> Münzen kaufst, automatisch einen Prozentsatz pro Tag ein. Wie in der Realität gilt: <strong>Je früher du investierst, desto mehr erhältst du</strong>. Anlagen haben <strong>keinen negativen Wert</strong>.',
    target_title:'🎯 Ziel-Simulator',
    target_sub:'Lege ein Münzziel fest und sieh, wie lange du brauchst, um es mit deinen aktuellen Dividenden zu erreichen.',
    target_obj:'Ziel:',
    tr_missing:'Fehlend', tr_daily:'Dividenden / Tag', tr_time:'Geschätzte Zeit', tr_progress:'Aktueller Fortschritt',
    tl_target:'Ziel', tl_now:'Jetzt',
    assets_title:'🏠 Verfügbare Anlagen',
    shop_title:'🛍 Shop', shop_sub:'Gib Münzen für Boni und Kosmetika aus',
    shop_coins_lbl:'Münzen verfügbar',
    ps_xp:'Gesamt-XP', ps_coins:'Münzen', ps_sessions:'Sitzungen',
    ps_streak:'🔥 Tage', ps_chapters:'Kapitel', ps_wealth:'💎 Vermögen',
    appearance:'🎨 Erscheinungsbild', lang_ui:'🌐 Oberflächensprache',
    btn_change_lang:'🌍 Sprache ändern', btn_logout:'🚪 Abmelden',
    qr_title:'📱 Kapitel teilen', btn_qr_copy:'📋 Kopieren', btn_close:'Schließen',
    langmodal_title:'Sprache ändern', lm_speak:'Ich spreche:', lm_learn:'Ich möchte lernen:',
    btn_apply:'Anwenden', btn_cancel:'Abbrechen',
    amod_market:'Echter Marktpreis', amod_position:'Deine Position',
    amod_units:'Besessene Einheiten', amod_value:'Aktueller Wert',
    amod_daily:'Dividenden / Tag', amod_pv:'Kursgewinn',
    btn_buy:'Kaufen', btn_sell:'Verkaufen',
    joined:'Mitglied seit ',
  },
  cs:{
    nav_learn:'Učit se', nav_portfolio:'Portfolio', nav_shop:'Obchod', nav_profile:'Profil',
    tagline:'Uč se. Investuj. Ovládni.',
    pick_theme:'Vyber si téma',
    theme_dark:'🌙 Tmavé', theme_light:'☀️ Světlé', theme_claude:'🤖 Claude', theme_random:'🎲 Náhodné',
    tab_login:'Přihlásit se', tab_register:'Registrovat se',
    lbl_pass:'Heslo', lbl_reg_name:'Jméno / Přezdívka', lbl_reg_email:'Email', lbl_reg_pass:'Heslo',
    btn_login:'Přihlásit se →', demo_link:'Demo →',
    btn_register:'Vytvořit účet 🚀',
    or_guest:'nebo pokračovat bez účtu',
    guest_btn:'👤 Pokračovat jako host', guest_warn:'Postup nebude uložen',
    ph_login_email:'tvuj@email.cz', ph_login_pass:'••••••••',
    ph_reg_name:'Jan', ph_reg_email:'tvuj@email.cz', ph_reg_pass:'Min. 6 znaků',
    learn_tagline:'Zvol svůj jazyk', i_speak:'🧑 Mluvím', i_learn:'🎯 Chci se naučit',
    btn_start:'Začít →',
    levels_sub:'Každá úroveň navazuje na předchozí slovní zásobu',
    mix_badge:'🎲 Doporučen smíšený režim',
    gtype_mixed:'Smíšený režim', gdesc_mixed:'Vše smíchané — nejlepší způsob učení',
    gtype_quiz:'Rychlý kvíz', gdesc_quiz:'4 možnosti · Časovač · Styl Kahoot',
    gtype_fill:'Doplnit', gdesc_fill:'Napiš slovo · Diakritika tolerována ✨',
    gtype_match:'Přiřadit', gdesc_match:'Spoj slova s jejich překlady',
    reward_mixed:'+30 mincí max', reward_quiz:'+15 mincí max', reward_fill:'+20 mincí max', reward_match:'+10 mincí max',
    ph_fill:'Napiš svou odpověď…',
    your_sent:'Tvá věta:', slot_placeholder:'Klikni na slova…', words_avail:'Dostupná slova:',
    pairs:'páry', btn_check:'Zkontrolovat ✓', btn_next:'Další →', btn_continue:'Pokračovat →',
    coins_won:'Získány mince!', coins_hint:'Použij je k investování do Portfolia',
    r_correct:'Správně', r_wrong:'Chyby',
    btn_replay:'Hrát znovu 🔄', btn_r_chapters:'Kapitoly', btn_r_invest:'$ Investovat',
    wealth_hero:'◈ Celkové jmění', liquid_coins:'Hotovostní mince', div_day:'Dividendy / den',
    invested:'Investováno', div_avail:'Dividendy k dispozici!',
    btn_collect:'Vybrat',
    div_explain_title:'📖 Jak fungují dividendy?',
    div_explain_body:'V reálném životě určité <strong>aktiva</strong> (zlato, nemovitosti, akcie) generují <strong>pravidelné</strong> příjmy, aniž by bylo nutné je prodávat. To jsou <span class="highlight">dividendy</span>.<br><br>Zde ti každé aktivum, které koupíš za své <span class="coin"></span> mince, automaticky přináší procento každý den. Jako ve skutečnosti platí: <strong>čím dříve investuješ, tím více dostaneš</strong>. Aktiva <strong>nemají zápornou hodnotu</strong>.',
    target_title:'🎯 Simulátor cíle',
    target_sub:'Nastav cíl v mincích a zjisti, jak dlouho bude trvat ho dosáhnout s tvými aktuálními dividendami.',
    target_obj:'Cíl:',
    tr_missing:'Chybí', tr_daily:'Dividendy / den', tr_time:'Odhadovaný čas', tr_progress:'Aktuální postup',
    tl_target:'Cíl', tl_now:'Nyní',
    assets_title:'🏠 Dostupná aktiva',
    shop_title:'🛍 Obchod', shop_sub:'Utrať mince za bonusy a kosmetiku',
    shop_coins_lbl:'dostupných mincí',
    ps_xp:'Celkem XP', ps_coins:'Mince', ps_sessions:'Sezení',
    ps_streak:'🔥 Dny', ps_chapters:'Kapitoly', ps_wealth:'💎 Jmění',
    appearance:'🎨 Vzhled', lang_ui:'🌐 Jazyk rozhraní',
    btn_change_lang:'🌍 Změnit jazyk', btn_logout:'🚪 Odhlásit se',
    qr_title:'📱 Sdílet tuto kapitolu', btn_qr_copy:'📋 Kopírovat', btn_close:'Zavřít',
    langmodal_title:'Změnit jazyk', lm_speak:'Mluvím:', lm_learn:'Chci se naučit:',
    btn_apply:'Použít', btn_cancel:'Zrušit',
    amod_market:'Skutečná tržní cena', amod_position:'Tvá pozice',
    amod_units:'Vlastněné jednotky', amod_value:'Aktuální hodnota',
    amod_daily:'Dividendy / den', amod_pv:'Kapitálový zisk',
    btn_buy:'Koupit', btn_sell:'Prodat',
    joined:'Člen od ',
  },
};
