// ══════════════════════════════════════════════
// DATA
// ══════════════════════════════════════════════
const LANGS={fr:{name:'Français',flag:'🇫🇷',native:'Français'},en:{name:'Anglais',flag:'🇬🇧',native:'English'},es:{name:'Espagnol',flag:'🇪🇸',native:'Español'},de:{name:'Allemand',flag:'🇩🇪',native:'Deutsch'},cs:{name:'Tchèque',flag:'🇨🇿',native:'Čeština'}};
const LEVELS=[{id:'A1',label:'A1 — Débutant',desc:'Salutations, chiffres, couleurs'},{id:'A2',label:'A2 — Élémentaire',desc:'Famille, nourriture, maison'},{id:'B1',label:'B1 — Intermédiaire',desc:'Voyages, passé & futur'},{id:'B2',label:'B2 — Avancé',desc:'Actualité, idiomes'},{id:'C1',label:'C1 — Expert',desc:'Argumentation, registres'},{id:'C2',label:'C2 — Maîtrise',desc:'Littérature, humour'}];
const WD={hello:{fr:'Bonjour',en:'Hello',es:'Hola',de:'Hallo',cs:'Ahoj'},goodbye:{fr:'Au revoir',en:'Goodbye',es:'Adiós',de:'Auf Wiedersehen',cs:'Na shledanou'},thanks:{fr:'Merci',en:'Thank you',es:'Gracias',de:'Danke',cs:'Děkuji'},please:{fr:'S\'il vous plaît',en:'Please',es:'Por favor',de:'Bitte',cs:'Prosím'},yes:{fr:'Oui',en:'Yes',es:'Sí',de:'Ja',cs:'Ano'},no:{fr:'Non',en:'No',es:'No',de:'Nein',cs:'Ne'},sorry:{fr:'Pardon',en:'Sorry',es:'Lo siento',de:'Entschuldigung',cs:'Promiňte'},excuse:{fr:'Excusez-moi',en:'Excuse me',es:'Permiso',de:'Verzeihung',cs:'S dovolením'},one:{fr:'Un',en:'One',es:'Uno',de:'Eins',cs:'Jeden'},two:{fr:'Deux',en:'Two',es:'Dos',de:'Zwei',cs:'Dva'},three:{fr:'Trois',en:'Three',es:'Tres',de:'Drei',cs:'Tři'},four:{fr:'Quatre',en:'Four',es:'Cuatro',de:'Vier',cs:'Čtyři'},five:{fr:'Cinq',en:'Five',es:'Cinco',de:'Fünf',cs:'Pět'},ten:{fr:'Dix',en:'Ten',es:'Diez',de:'Zehn',cs:'Deset'},twenty:{fr:'Vingt',en:'Twenty',es:'Veinte',de:'Zwanzig',cs:'Dvacet'},hundred:{fr:'Cent',en:'Hundred',es:'Cien',de:'Hundert',cs:'Sto'},red:{fr:'Rouge',en:'Red',es:'Rojo',de:'Rot',cs:'Červená'},blue:{fr:'Bleu',en:'Blue',es:'Azul',de:'Blau',cs:'Modrá'},green:{fr:'Vert',en:'Green',es:'Verde',de:'Grün',cs:'Zelená'},yellow:{fr:'Jaune',en:'Yellow',es:'Amarillo',de:'Gelb',cs:'Žlutá'},black:{fr:'Noir',en:'Black',es:'Negro',de:'Schwarz',cs:'Černá'},white:{fr:'Blanc',en:'White',es:'Blanco',de:'Weiß',cs:'Bílá'},orange:{fr:'Orange',en:'Orange',es:'Naranja',de:'Orange',cs:'Oranžová'},pink:{fr:'Rose',en:'Pink',es:'Rosa',de:'Rosa',cs:'Růžová'},father:{fr:'Père',en:'Father',es:'Padre',de:'Vater',cs:'Otec'},mother:{fr:'Mère',en:'Mother',es:'Madre',de:'Mutter',cs:'Matka'},brother:{fr:'Frère',en:'Brother',es:'Hermano',de:'Bruder',cs:'Bratr'},sister:{fr:'Sœur',en:'Sister',es:'Hermana',de:'Schwester',cs:'Sestra'},grandfather:{fr:'Grand-père',en:'Grandfather',es:'Abuelo',de:'Großvater',cs:'Dědeček'},grandmother:{fr:'Grand-mère',en:'Grandmother',es:'Abuela',de:'Großmutter',cs:'Babička'},child:{fr:'Enfant',en:'Child',es:'Hijo',de:'Kind',cs:'Dítě'},cousin:{fr:'Cousin',en:'Cousin',es:'Primo',de:'Cousin',cs:'Bratranec'},bread:{fr:'Pain',en:'Bread',es:'Pan',de:'Brot',cs:'Chléb'},water:{fr:'Eau',en:'Water',es:'Agua',de:'Wasser',cs:'Voda'},coffee:{fr:'Café',en:'Coffee',es:'Café',de:'Kaffee',cs:'Káva'},wine:{fr:'Vin',en:'Wine',es:'Vino',de:'Wein',cs:'Víno'},meat:{fr:'Viande',en:'Meat',es:'Carne',de:'Fleisch',cs:'Maso'},fish:{fr:'Poisson',en:'Fish',es:'Pescado',de:'Fisch',cs:'Ryba'},fruit:{fr:'Fruit',en:'Fruit',es:'Fruta',de:'Frucht',cs:'Ovoce'},cheese:{fr:'Fromage',en:'Cheese',es:'Queso',de:'Käse',cs:'Sýr'},plane:{fr:'Avion',en:'Plane',es:'Avión',de:'Flugzeug',cs:'Letadlo'},train:{fr:'Train',en:'Train',es:'Tren',de:'Zug',cs:'Vlak'},hotel:{fr:'Hôtel',en:'Hotel',es:'Hotel',de:'Hotel',cs:'Hotel'},passport:{fr:'Passeport',en:'Passport',es:'Pasaporte',de:'Reisepass',cs:'Pas'},ticket:{fr:'Billet',en:'Ticket',es:'Billete',de:'Fahrkarte',cs:'Jízdenka'},suitcase:{fr:'Valise',en:'Suitcase',es:'Maleta',de:'Koffer',cs:'Kufr'},airport:{fr:'Aéroport',en:'Airport',es:'Aeropuerto',de:'Flughafen',cs:'Letiště'},reservation:{fr:'Réservation',en:'Booking',es:'Reserva',de:'Buchung',cs:'Rezervace'}};
const CHAPTERS={A1:[{id:'A1-1',title:{fr:'Salutations',en:'Greetings',es:'Saludos',de:'Begrüßung',cs:'Pozdravy'},subtitle:{fr:'Se présenter',en:'Meet people',es:'Presentarse',de:'Vorstellen',cs:'Predstavit se'},wids:['hello','goodbye','thanks','please','yes','no','sorry','excuse'],sents:{fr:['Je m appelle Marie','Comment tu t appelles','Enchante de te connaitre'],en:['My name is Tom','What is your name','Nice to meet you'],es:['Me llamo Carlos','Como te llamas','Encantado de conocerte'],de:['Ich heisse Klaus','Wie heisst du','Schon dich kennenzulernen'],cs:['Jmenuji se Marie','Jak se jmenujes','Rad te poznavam']}},{id:'A1-2',title:{fr:'Les Chiffres',en:'Numbers',es:'Números',de:'Zahlen',cs:'Čísla'},subtitle:{fr:'Compter de 1 à 100',en:'Count 1–100',es:'Contar 1–100',de:'Zählen 1–100',cs:'Počítat 1–100'},wids:['one','two','three','four','five','ten','twenty','hundred'],sents:{fr:['J ai vingt ans','Combien coute ce livre','Il est dix heures'],en:['I am twenty years old','How much is this book','It is ten o clock'],es:['Tengo veinte anos','Cuanto cuesta este libro','Son las diez'],de:['Ich bin zwanzig Jahre alt','Wie viel kostet dieses Buch','Es ist zehn Uhr'],cs:['Je mi dvacet let','Kolik stoji tato kniha','Je deset hodin']}},{id:'A1-3',title:{fr:'Les Couleurs',en:'Colours',es:'Colores',de:'Farben',cs:'Barvy'},subtitle:{fr:'Décrire avec les couleurs',en:'Describe with colours',es:'Describir con colores',de:'Mit Farben beschreiben',cs:'Popisovat barvami'},wids:['red','blue','green','yellow','black','white','orange','pink'],sents:{fr:['Le ciel est bleu','Ma voiture est rouge','J aime la couleur verte'],en:['The sky is blue','My car is red','I like the colour green'],es:['El cielo es azul','Mi coche es rojo','Me gusta el color verde'],de:['Der Himmel ist blau','Mein Auto ist rot','Ich mag die Farbe Grun'],cs:['Nebe je modre','Moje auto je cervene','Mam rad zelenou barvu']}}],A2:[{id:'A2-1',title:{fr:'La Famille',en:'Family',es:'La Familia',de:'Familie',cs:'Rodina'},subtitle:{fr:'Parler de sa famille',en:'Talk about your family',es:'Hablar de la familia',de:'Über Familie sprechen',cs:'Mluvit o rodině'},wids:['father','mother','brother','sister','grandfather','grandmother','child','cousin'],sents:{fr:['J ai deux freres et une soeur','Mon pere est medecin','Ma famille est grande'],en:['I have two brothers and a sister','My father is a doctor','My family is big'],es:['Tengo dos hermanos y una hermana','Mi padre es medico','Mi familia es grande'],de:['Ich habe zwei Bruder und eine Schwester','Mein Vater ist Arzt','Meine Familie ist gross'],cs:['Mam dva bratry a sestru','Muj otec je lekar','Moje rodina je velka']}},{id:'A2-2',title:{fr:'La Nourriture',en:'Food & Drink',es:'Comida',de:'Essen',cs:'Jídlo'},subtitle:{fr:'Commander de la nourriture',en:'Order food',es:'Pedir comida',de:'Essen bestellen',cs:'Objednat jídlo'},wids:['bread','water','coffee','wine','meat','fish','fruit','cheese'],sents:{fr:['Je voudrais un cafe','L addition s il vous plait','Le poisson est tres bon'],en:['I would like a coffee please','The bill please','The fish is very good'],es:['Quisiera un cafe por favor','La cuenta por favor','El pescado esta muy bueno'],de:['Ich hatte gerne einen Kaffee','Die Rechnung bitte','Der Fisch ist sehr gut'],cs:['Chtel bych kavu prosim','Ucet prosim','Ryba je velmi dobra']}}],B1:[{id:'B1-1',title:{fr:'Les Voyages',en:'Travel',es:'Viajes',de:'Reisen',cs:'Cestování'},subtitle:{fr:'Voyager et se déplacer',en:'Getting around',es:'Viajar',de:'Reisen',cs:'Cestovat'},wids:['plane','train','hotel','passport','ticket','suitcase','airport','reservation'],sents:{fr:['Mon vol est retarde de deux heures','J ai reserve une chambre pour trois nuits','Ou est l aeroport'],en:['My flight is delayed by two hours','I have booked a room for three nights','Where is the airport'],es:['Mi vuelo lleva dos horas de retraso','He reservado una habitacion por tres noches','Donde esta el aeropuerto'],de:['Mein Flug hat zwei Stunden Verspatung','Ich habe ein Zimmer fur drei Nachte gebucht','Wo ist der Flughafen'],cs:['Muj let ma dvouhodinove zpozdeni','Rezervoval jsem pokoj na tri noci','Kde je letiste']}}]};

// ASSETS (real-world inspired, always positive growth)
const ASSET_DEFS=[
  {id:'gold',name:'Or',icon:'<svg width="32" height="32" viewBox="0 0 32 32"><circle cx="16" cy="16" r="14" fill="url(#gi)" stroke="#b45309" stroke-width="1.5"/><text x="16" y="21" text-anchor="middle" font-size="14" font-weight="900" fill="#7c2d12">Au</text><defs><radialGradient id="gi" cx="35%" cy="35%"><stop offset="0%" stop-color="#ffe066"/><stop offset="100%" stop-color="#d97706"/></radialGradient></defs></svg>',type:'Métal précieux',class:'gold',cost:50,divRate:0.02,growthRate:0.001,desc:'L\'or conserve sa valeur depuis des millénaires. Jamais à zéro.',explain:'L\'or est un actif réel. Sa valeur augmente légèrement chaque jour. Il verse 2% de dividendes par investissement.'},
  {id:'house',name:'Immeuble',icon:'<svg width="32" height="32" viewBox="0 0 32 32"><polygon points="16,4 28,16 24,16 24,28 8,28 8,16 4,16" fill="#0ea5e9" stroke="#0369a1" stroke-width="1.5" stroke-linejoin="round"/><rect x="13" y="20" width="6" height="8" fill="#7dd3fc"/></svg>',type:'Immobilier',class:'house',cost:150,divRate:0.04,growthRate:0.0008,desc:'L\'immobilier génère des loyers réguliers. Prix jamais négatif.',explain:'Les loyers = dividendes. La valeur des biens immobiliers croît historiquement. Taux : 4%/j par niveau.'},
  {id:'stock',name:'Actions',icon:'<svg width="32" height="32" viewBox="0 0 32 32"><rect x="2" y="2" width="28" height="28" rx="4" fill="#064e3b"/><polyline points="5,24 11,16 17,20 27,8" fill="none" stroke="#34d399" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/><circle cx="27" cy="8" r="2.5" fill="#34d399"/></svg>',type:'Marché actions',class:'stock',cost:80,divRate:0.03,growthRate:0.0012,desc:'Les grandes entreprises partagent leurs bénéfices.',explain:'Les actions versent des dividendes trimestriels. Ici, tu reçois 3% de ta mise par jour.'},
  {id:'crypto',name:'Crypto Index',icon:'<svg width="32" height="32" viewBox="0 0 32 32"><polygon points="16,2 30,10 30,22 16,30 2,22 2,10" fill="url(#ci)" stroke="#6d28d9" stroke-width="1.5"/><text x="16" y="21" text-anchor="middle" font-size="11" font-weight="900" fill="#ede9fe">IDX</text><defs><radialGradient id="ci" cx="35%" cy="35%"><stop offset="0%" stop-color="#a78bfa"/><stop offset="100%" stop-color="#7c3aed"/></radialGradient></defs></svg>',type:'Actif digital',class:'crypto',cost:30,divRate:0.015,growthRate:0.002,desc:'Panier d\'actifs digitaux. Volatil mais toujours un plancher non nul.',explain:'Représente un indice crypto diversifié. Croissance rapide mais dividende plus faible (1.5%/j).'},
];

// SHOP ITEMS
const SHOP_ITEMS=[
  {id:'streak_shield',name:'Bouclier Série',icon:'🛡️',price:40,desc:'Protège ta série 1 fois si tu rates un jour',type:'consumable'},
  {id:'xp_boost',name:'Boost XP ×2',icon:'⚡',price:60,desc:'Double tes XP pendant 3 sessions',type:'consumable'},
  {id:'hint_pack',name:'Pack Indices',icon:'💡',price:25,desc:'5 indices gratuits pour les questions difficiles',type:'consumable'},
  {id:'avatar_gold',name:'Avatar Doré',icon:'👑',price:100,desc:'Badge exclusif sur ton profil',type:'cosmetic'},
  {id:'avatar_diamond',name:'Avatar Diamant',icon:'💎',price:200,desc:'Le badge le plus rare de LinguaQuest',type:'cosmetic'},
  {id:'bonus_coins',name:'Bonus Pièces',icon:'<span class="coin"></span>',price:0,desc:'Reçois 50 pièces bonus chaque semaine',type:'premium'},
];

// ══════════════════════════════════════════════
// UI STRINGS — full interface translations
// ══════════════════════════════════════════════
const UI_STRINGS = {
  fr:{
    // nav
    nav_learn:'Apprendre', nav_portfolio:'Portfolio', nav_shop:'Boutique', nav_profile:'Profil',
    // tagline / theme picker
    tagline:'Apprends. Investis. Maîtrise.',
    pick_theme:'Choisis ton thème',
    theme_dark:'🌙 Sombre', theme_light:'☀️ Clair', theme_claude:'🤖 Claude', theme_random:'🎲 Aléatoire',
    // auth
    tab_login:'Se connecter', tab_register:"S'inscrire",
    lbl_pass:'Mot de passe', lbl_reg_name:'Prénom / Pseudo', lbl_reg_email:'Email', lbl_reg_pass:'Mot de passe',
    btn_login:'Se connecter →', demo_link:'Connexion démo →',
    btn_register:'Créer mon compte 🚀',
    or_guest:'ou continuer sans compte',
    guest_btn:'👤 Continuer en invité', guest_warn:'La progression ne sera pas sauvegardée',
    ph_login_email:'ton@email.com', ph_login_pass:'••••••••',
    ph_reg_name:'Marie', ph_reg_email:'ton@email.com', ph_reg_pass:'Min. 6 caractères',
    // learn
    learn_tagline:'Choisis ta langue', i_speak:'🧑 Je parle', i_learn:'🎯 Je veux apprendre',
    btn_start:'Commencer →',
    // levels
    levels_sub:'Chaque niveau réutilise le vocabulaire précédent',
    // game select
    mix_badge:'🎲 Mode Mixte recommandé',
    gtype_mixed:'Mode Mixte', gdesc_mixed:"Tout mélangé — la meilleure façon d'apprendre",
    gtype_quiz:'Quiz Rapide', gdesc_quiz:'4 choix · Chrono · Style Kahoot',
    gtype_fill:'Compléter', gdesc_fill:'Tape le mot · Accents tolérés ✨',
    gtype_match:'Associer', gdesc_match:'Relie les mots et traductions',
    reward_mixed:'+30 pièces max', reward_quiz:'+15 pièces max', reward_fill:'+20 pièces max', reward_match:'+10 pièces max',
    // game
    ph_fill:'Écris ta réponse…',
    your_sent:'Ta phrase :', slot_placeholder:'Clique sur les mots…', words_avail:'Mots disponibles :',
    pairs:'paires', btn_check:'Vérifier ✓', btn_next:'Suivant →', btn_continue:'Continuer →',
    // results
    coins_won:'Pièces gagnées !', coins_hint:'Utilise-les pour investir dans le Portfolio',
    r_correct:'Correct', r_wrong:'Erreurs',
    btn_replay:'Rejouer 🔄', btn_r_chapters:'Chapitres', btn_r_invest:'$ Investir',
    // portfolio
    wealth_hero:'◈ Patrimoine total', liquid_coins:'Pièces liquides', div_day:'Dividendes / jour',
    invested:'Investi', div_avail:'Dividendes disponibles !',
    btn_collect:'Collecter',
    div_explain_title:'📖 Comment fonctionnent les dividendes ?',
    div_explain_body:"Dans la vraie vie, certains <strong>actifs</strong> (or, immobilier, actions) génèrent des revenus <strong>réguliers</strong> sans que tu doives les vendre. C'est ça un <span class=\"highlight\">dividende</span>.<br><br>Ici, chaque actif que tu achètes avec tes <span class=\"coin\"></span> pièces te rapporte automatiquement un pourcentage chaque jour. Comme dans la réalité, <strong>plus tu investis tôt, plus tu reçois</strong>. Les actifs <strong>n'ont pas de valeur négative</strong> — ils peuvent stagner ou croître, jamais disparaître.",
    target_title:'🎯 Simulateur d\'objectif',
    target_sub:"Fixe un objectif en pièces et vois combien de temps il faudra pour l'atteindre avec tes dividendes actuels.",
    target_obj:'Objectif :',
    tr_missing:'Il manque', tr_daily:'Dividendes / jour', tr_time:'Temps estimé', tr_progress:'Progression actuelle',
    tl_target:'Objectif', tl_now:'Maintenant',
    assets_title:'🏠 Actifs disponibles',
    // shop
    shop_title:'🛍 Boutique', shop_sub:'Dépense tes pièces pour des bonus et cosmétiques',
    shop_coins_lbl:'pièces disponibles',
    // profile
    ps_xp:'XP Total', ps_coins:'Pièces', ps_sessions:'Sessions',
    ps_streak:'🔥 Jours', ps_chapters:'Chapitres', ps_wealth:'💎 Patrimoine',
    appearance:'🎨 Apparence', lang_ui:"🌐 Langue de l'interface",
    btn_change_lang:'🌍 Changer de langue', btn_logout:'🚪 Se déconnecter',
    // qr modal
    qr_title:'📱 Partager ce chapitre', btn_qr_copy:'📋 Copier', btn_close:'Fermer',
    // lang modal
    langmodal_title:'Changer de langue', lm_speak:'Je parle :', lm_learn:"J'apprends :",
    btn_apply:'Appliquer', btn_cancel:'Annuler',
    // asset modal
    amod_market:'Prix marché réel', amod_position:'Ta position',
    amod_units:'Unités possédées', amod_value:'Valeur actuelle',
    amod_daily:'Dividendes / jour', amod_pv:'Plus-value',
    btn_buy:'Acheter', btn_sell:'Vendre',
    // joined
    joined:'Membre depuis ',
  },
  en:{
    nav_learn:'Learn', nav_portfolio:'Portfolio', nav_shop:'Shop', nav_profile:'Profile',
    tagline:'Learn. Invest. Master.',
    pick_theme:'Choose your theme',
    theme_dark:'🌙 Dark', theme_light:'☀️ Light', theme_claude:'🤖 Claude', theme_random:'🎲 Random',
    tab_login:'Log in', tab_register:'Sign up',
    lbl_pass:'Password', lbl_reg_name:'Name / Username', lbl_reg_email:'Email', lbl_reg_pass:'Password',
    btn_login:'Log in →', demo_link:'Demo login →',
    btn_register:'Create account 🚀',
    or_guest:'or continue without account',
    guest_btn:'👤 Continue as guest', guest_warn:'Progress will not be saved',
    ph_login_email:'your@email.com', ph_login_pass:'••••••••',
    ph_reg_name:'Alex', ph_reg_email:'your@email.com', ph_reg_pass:'Min. 6 characters',
    learn_tagline:'Choose your language', i_speak:'🧑 I speak', i_learn:'🎯 I want to learn',
    btn_start:'Start →',
    levels_sub:'Each level builds on previous vocabulary',
    mix_badge:'🎲 Mixed mode recommended',
    gtype_mixed:'Mixed Mode', gdesc_mixed:'All mixed — the best way to learn',
    gtype_quiz:'Quick Quiz', gdesc_quiz:'4 choices · Timer · Kahoot style',
    gtype_fill:'Fill in', gdesc_fill:'Type the word · Accents tolerated ✨',
    gtype_match:'Match', gdesc_match:'Link words and their translations',
    reward_mixed:'+30 coins max', reward_quiz:'+15 coins max', reward_fill:'+20 coins max', reward_match:'+10 coins max',
    ph_fill:'Write your answer…',
    your_sent:'Your sentence:', slot_placeholder:'Click on words…', words_avail:'Available words:',
    pairs:'pairs', btn_check:'Check ✓', btn_next:'Next →', btn_continue:'Continue →',
    coins_won:'Coins earned!', coins_hint:'Use them to invest in your Portfolio',
    r_correct:'Correct', r_wrong:'Wrong',
    btn_replay:'Play again 🔄', btn_r_chapters:'Chapters', btn_r_invest:'$ Invest',
    wealth_hero:'◈ Total wealth', liquid_coins:'Liquid coins', div_day:'Dividends / day',
    invested:'Invested', div_avail:'Dividends available!',
    btn_collect:'Collect',
    div_explain_title:'📖 How do dividends work?',
    div_explain_body:'In real life, some <strong>assets</strong> (gold, real estate, stocks) generate <strong>regular</strong> income without having to sell them. That is a <span class="highlight">dividend</span>.<br><br>Here, each asset you buy with your <span class="coin"></span> coins automatically earns you a percentage each day. As in real life, <strong>the earlier you invest, the more you earn</strong>. Assets <strong>never go negative</strong> — they may stagnate or grow, but never disappear.',
    target_title:'🎯 Goal simulator',
    target_sub:'Set a coin target and see how long it will take to reach it with your current dividends.',
    target_obj:'Target:',
    tr_missing:'Missing', tr_daily:'Dividends / day', tr_time:'Estimated time', tr_progress:'Current progress',
    tl_target:'Target', tl_now:'Now',
    assets_title:'🏠 Available assets',
    shop_title:'🛍 Shop', shop_sub:'Spend your coins on bonuses and cosmetics',
    shop_coins_lbl:'coins available',
    ps_xp:'Total XP', ps_coins:'Coins', ps_sessions:'Sessions',
    ps_streak:'🔥 Days', ps_chapters:'Chapters', ps_wealth:'💎 Wealth',
    appearance:'🎨 Appearance', lang_ui:'🌐 Interface language',
    btn_change_lang:'🌍 Change language', btn_logout:'🚪 Log out',
    qr_title:'📱 Share this chapter', btn_qr_copy:'📋 Copy', btn_close:'Close',
    langmodal_title:'Change language', lm_speak:'I speak:', lm_learn:'I want to learn:',
    btn_apply:'Apply', btn_cancel:'Cancel',
    amod_market:'Real market price', amod_position:'Your position',
    amod_units:'Units owned', amod_value:'Current value',
    amod_daily:'Dividends / day', amod_pv:'Capital gain',
    btn_buy:'Buy', btn_sell:'Sell',
    joined:'Member since ',
  },
  es:{
    nav_learn:'Aprender', nav_portfolio:'Portafolio', nav_shop:'Tienda', nav_profile:'Perfil',
    tagline:'Aprende. Invierte. Domina.',
    pick_theme:'Elige tu tema',
    theme_dark:'🌙 Oscuro', theme_light:'☀️ Claro', theme_claude:'🤖 Claude', theme_random:'🎲 Aleatorio',
    tab_login:'Iniciar sesión', tab_register:'Registrarse',
    lbl_pass:'Contraseña', lbl_reg_name:'Nombre / Usuario', lbl_reg_email:'Email', lbl_reg_pass:'Contraseña',
    btn_login:'Iniciar sesión →', demo_link:'Demo →',
    btn_register:'Crear cuenta 🚀',
    or_guest:'o continuar sin cuenta',
    guest_btn:'👤 Continuar como invitado', guest_warn:'El progreso no se guardará',
    ph_login_email:'tu@email.com', ph_login_pass:'••••••••',
    ph_reg_name:'Carlos', ph_reg_email:'tu@email.com', ph_reg_pass:'Mín. 6 caracteres',
    learn_tagline:'Elige tu idioma', i_speak:'🧑 Hablo', i_learn:'🎯 Quiero aprender',
    btn_start:'Empezar →',
    levels_sub:'Cada nivel reutiliza el vocabulario anterior',
    mix_badge:'🎲 Modo mixto recomendado',
    gtype_mixed:'Modo Mixto', gdesc_mixed:'Todo mezclado — la mejor forma de aprender',
    gtype_quiz:'Quiz Rápido', gdesc_quiz:'4 opciones · Cronómetro · Estilo Kahoot',
    gtype_fill:'Completar', gdesc_fill:'Escribe la palabra · Acentos tolerados ✨',
    gtype_match:'Asociar', gdesc_match:'Une las palabras con sus traducciones',
    reward_mixed:'+30 monedas máx', reward_quiz:'+15 monedas máx', reward_fill:'+20 monedas máx', reward_match:'+10 monedas máx',
    ph_fill:'Escribe tu respuesta…',
    your_sent:'Tu frase:', slot_placeholder:'Haz clic en las palabras…', words_avail:'Palabras disponibles:',
    pairs:'pares', btn_check:'Verificar ✓', btn_next:'Siguiente →', btn_continue:'Continuar →',
    coins_won:'¡Monedas ganadas!', coins_hint:'Úsalas para invertir en tu Portafolio',
    r_correct:'Correcto', r_wrong:'Errores',
    btn_replay:'Repetir 🔄', btn_r_chapters:'Capítulos', btn_r_invest:'$ Invertir',
    wealth_hero:'◈ Patrimonio total', liquid_coins:'Monedas líquidas', div_day:'Dividendos / día',
    invested:'Invertido', div_avail:'¡Dividendos disponibles!',
    btn_collect:'Cobrar',
    div_explain_title:'📖 ¿Cómo funcionan los dividendos?',
    div_explain_body:'En la vida real, ciertos <strong>activos</strong> (oro, inmuebles, acciones) generan ingresos <strong>regulares</strong> sin necesidad de venderlos. Eso es un <span class="highlight">dividendo</span>.<br><br>Aquí, cada activo que compras con tus <span class="coin"></span> monedas te genera automáticamente un porcentaje cada día. Como en la realidad, <strong>cuanto antes inviertas, más recibirás</strong>. Los activos <strong>nunca tienen valor negativo</strong>.',
    target_title:'🎯 Simulador de objetivo',
    target_sub:'Fija un objetivo en monedas y mira cuánto tiempo tardarás en alcanzarlo con tus dividendos actuales.',
    target_obj:'Objetivo:',
    tr_missing:'Faltan', tr_daily:'Dividendos / día', tr_time:'Tiempo estimado', tr_progress:'Progreso actual',
    tl_target:'Objetivo', tl_now:'Ahora',
    assets_title:'🏠 Activos disponibles',
    shop_title:'🛍 Tienda', shop_sub:'Gasta tus monedas en bonificaciones y cosméticos',
    shop_coins_lbl:'monedas disponibles',
    ps_xp:'XP Total', ps_coins:'Monedas', ps_sessions:'Sesiones',
    ps_streak:'🔥 Días', ps_chapters:'Capítulos', ps_wealth:'💎 Patrimonio',
    appearance:'🎨 Apariencia', lang_ui:'🌐 Idioma de la interfaz',
    btn_change_lang:'🌍 Cambiar idioma', btn_logout:'🚪 Cerrar sesión',
    qr_title:'📱 Compartir este capítulo', btn_qr_copy:'📋 Copiar', btn_close:'Cerrar',
    langmodal_title:'Cambiar idioma', lm_speak:'Hablo:', lm_learn:'Quiero aprender:',
    btn_apply:'Aplicar', btn_cancel:'Cancelar',
    amod_market:'Precio de mercado real', amod_position:'Tu posición',
    amod_units:'Unidades poseídas', amod_value:'Valor actual',
    amod_daily:'Dividendos / día', amod_pv:'Plusvalía',
    btn_buy:'Comprar', btn_sell:'Vender',
    joined:'Miembro desde ',
  },
  de:{
    nav_learn:'Lernen', nav_portfolio:'Portfolio', nav_shop:'Shop', nav_profile:'Profil',
    tagline:'Lernen. Investieren. Meistern.',
    pick_theme:'Wähle dein Thema',
    theme_dark:'🌙 Dunkel', theme_light:'☀️ Hell', theme_claude:'🤖 Claude', theme_random:'🎲 Zufällig',
    tab_login:'Anmelden', tab_register:'Registrieren',
    lbl_pass:'Passwort', lbl_reg_name:'Name / Benutzername', lbl_reg_email:'E-Mail', lbl_reg_pass:'Passwort',
    btn_login:'Anmelden →', demo_link:'Demo →',
    btn_register:'Konto erstellen 🚀',
    or_guest:'oder ohne Konto fortfahren',
    guest_btn:'👤 Als Gast fortfahren', guest_warn:'Fortschritt wird nicht gespeichert',
    ph_login_email:'deine@email.de', ph_login_pass:'••••••••',
    ph_reg_name:'Klaus', ph_reg_email:'deine@email.de', ph_reg_pass:'Mind. 6 Zeichen',
    learn_tagline:'Wähle deine Sprache', i_speak:'🧑 Ich spreche', i_learn:'🎯 Ich möchte lernen',
    btn_start:'Starten →',
    levels_sub:'Jede Stufe baut auf vorherigem Wortschatz auf',
    mix_badge:'🎲 Gemischter Modus empfohlen',
    gtype_mixed:'Gemischter Modus', gdesc_mixed:'Alles gemischt — die beste Lernmethode',
    gtype_quiz:'Schnell-Quiz', gdesc_quiz:'4 Optionen · Timer · Kahoot-Stil',
    gtype_fill:'Ergänzen', gdesc_fill:'Wort eingeben · Akzente toleriert ✨',
    gtype_match:'Zuordnen', gdesc_match:'Wörter mit Übersetzungen verbinden',
    reward_mixed:'+30 Münzen max', reward_quiz:'+15 Münzen max', reward_fill:'+20 Münzen max', reward_match:'+10 Münzen max',
    ph_fill:'Schreibe deine Antwort…',
    your_sent:'Dein Satz:', slot_placeholder:'Klicke auf Wörter…', words_avail:'Verfügbare Wörter:',
    pairs:'Paare', btn_check:'Prüfen ✓', btn_next:'Weiter →', btn_continue:'Fortfahren →',
    coins_won:'Münzen verdient!', coins_hint:'Nutze sie für Investitionen im Portfolio',
    r_correct:'Richtig', r_wrong:'Fehler',
    btn_replay:'Nochmal 🔄', btn_r_chapters:'Kapitel', btn_r_invest:'$ Investieren',
    wealth_hero:'◈ Gesamtvermögen', liquid_coins:'Flüssige Münzen', div_day:'Dividenden / Tag',
    invested:'Investiert', div_avail:'Dividenden verfügbar!',
    btn_collect:'Einsammeln',
    div_explain_title:'📖 Wie funktionieren Dividenden?',
    div_explain_body:'Im echten Leben erzeugen bestimmte <strong>Anlagen</strong> (Gold, Immobilien, Aktien) <strong>regelmäßige</strong> Einnahmen, ohne sie verkaufen zu müssen. Das ist eine <span class="highlight">Dividende</span>.<br><br>Hier bringt dir jede Anlage, die du mit deinen <span class="coin"></span> Münzen kaufst, automatisch einen Prozentsatz pro Tag ein. Wie in der Realität gilt: <strong>Je früher du investierst, desto mehr erhältst du</strong>. Anlagen haben <strong>keinen negativen Wert</strong>.',
    target_title:'🎯 Ziel-Simulator',
    target_sub:'Lege ein Münzziel fest und sieh, wie lange du brauchst, um es mit deinen aktuellen Dividenden zu erreichen.',
    target_obj:'Ziel:',
    tr_missing:'Fehlend', tr_daily:'Dividenden / Tag', tr_time:'Geschätzte Zeit', tr_progress:'Aktueller Fortschritt',
    tl_target:'Ziel', tl_now:'Jetzt',
    assets_title:'🏠 Verfügbare Anlagen',
    shop_title:'🛍 Shop', shop_sub:'Gib Münzen für Boni und Kosmetika aus',
    shop_coins_lbl:'Münzen verfügbar',
    ps_xp:'Gesamt-XP', ps_coins:'Münzen', ps_sessions:'Sitzungen',
    ps_streak:'🔥 Tage', ps_chapters:'Kapitel', ps_wealth:'💎 Vermögen',
    appearance:'🎨 Erscheinungsbild', lang_ui:'🌐 Oberflächensprache',
    btn_change_lang:'🌍 Sprache ändern', btn_logout:'🚪 Abmelden',
    qr_title:'📱 Kapitel teilen', btn_qr_copy:'📋 Kopieren', btn_close:'Schließen',
    langmodal_title:'Sprache ändern', lm_speak:'Ich spreche:', lm_learn:'Ich möchte lernen:',
    btn_apply:'Anwenden', btn_cancel:'Abbrechen',
    amod_market:'Echter Marktpreis', amod_position:'Deine Position',
    amod_units:'Besessene Einheiten', amod_value:'Aktueller Wert',
    amod_daily:'Dividenden / Tag', amod_pv:'Kursgewinn',
    btn_buy:'Kaufen', btn_sell:'Verkaufen',
    joined:'Mitglied seit ',
  },
  cs:{
    nav_learn:'Učit se', nav_portfolio:'Portfolio', nav_shop:'Obchod', nav_profile:'Profil',
    tagline:'Uč se. Investuj. Ovládni.',
    pick_theme:'Vyber si téma',
    theme_dark:'🌙 Tmavé', theme_light:'☀️ Světlé', theme_claude:'🤖 Claude', theme_random:'🎲 Náhodné',
    tab_login:'Přihlásit se', tab_register:'Registrovat se',
    lbl_pass:'Heslo', lbl_reg_name:'Jméno / Přezdívka', lbl_reg_email:'Email', lbl_reg_pass:'Heslo',
    btn_login:'Přihlásit se →', demo_link:'Demo →',
    btn_register:'Vytvořit účet 🚀',
    or_guest:'nebo pokračovat bez účtu',
    guest_btn:'👤 Pokračovat jako host', guest_warn:'Postup nebude uložen',
    ph_login_email:'tvuj@email.cz', ph_login_pass:'••••••••',
    ph_reg_name:'Jan', ph_reg_email:'tvuj@email.cz', ph_reg_pass:'Min. 6 znaků',
    learn_tagline:'Zvol svůj jazyk', i_speak:'🧑 Mluvím', i_learn:'🎯 Chci se naučit',
    btn_start:'Začít →',
    levels_sub:'Každá úroveň navazuje na předchozí slovní zásobu',
    mix_badge:'🎲 Doporučen smíšený režim',
    gtype_mixed:'Smíšený režim', gdesc_mixed:'Vše smíchané — nejlepší způsob učení',
    gtype_quiz:'Rychlý kvíz', gdesc_quiz:'4 možnosti · Časovač · Styl Kahoot',
    gtype_fill:'Doplnit', gdesc_fill:'Napiš slovo · Diakritika tolerována ✨',
    gtype_match:'Přiřadit', gdesc_match:'Spoj slova s jejich překlady',
    reward_mixed:'+30 mincí max', reward_quiz:'+15 mincí max', reward_fill:'+20 mincí max', reward_match:'+10 mincí max',
    ph_fill:'Napiš svou odpověď…',
    your_sent:'Tvá věta:', slot_placeholder:'Klikni na slova…', words_avail:'Dostupná slova:',
    pairs:'páry', btn_check:'Zkontrolovat ✓', btn_next:'Další →', btn_continue:'Pokračovat →',
    coins_won:'Získány mince!', coins_hint:'Použij je k investování do Portfolia',
    r_correct:'Správně', r_wrong:'Chyby',
    btn_replay:'Hrát znovu 🔄', btn_r_chapters:'Kapitoly', btn_r_invest:'$ Investovat',
    wealth_hero:'◈ Celkové jmění', liquid_coins:'Hotovostní mince', div_day:'Dividendy / den',
    invested:'Investováno', div_avail:'Dividendy k dispozici!',
    btn_collect:'Vybrat',
    div_explain_title:'📖 Jak fungují dividendy?',
    div_explain_body:'V reálném životě určité <strong>aktiva</strong> (zlato, nemovitosti, akcie) generují <strong>pravidelné</strong> příjmy, aniž by bylo nutné je prodávat. To jsou <span class="highlight">dividendy</span>.<br><br>Zde ti každé aktivum, které koupíš za své <span class="coin"></span> mince, automaticky přináší procento každý den. Jako ve skutečnosti platí: <strong>čím dříve investuješ, tím více dostaneš</strong>. Aktiva <strong>nemají zápornou hodnotu</strong>.',
    target_title:'🎯 Simulátor cíle',
    target_sub:'Nastav cíl v mincích a zjisti, jak dlouho bude trvat ho dosáhnout s tvými aktuálními dividendami.',
    target_obj:'Cíl:',
    tr_missing:'Chybí', tr_daily:'Dividendy / den', tr_time:'Odhadovaný čas', tr_progress:'Aktuální postup',
    tl_target:'Cíl', tl_now:'Nyní',
    assets_title:'🏠 Dostupná aktiva',
    shop_title:'🛍 Obchod', shop_sub:'Utrať mince za bonusy a kosmetiku',
    shop_coins_lbl:'dostupných mincí',
    ps_xp:'Celkem XP', ps_coins:'Mince', ps_sessions:'Sezení',
    ps_streak:'🔥 Dny', ps_chapters:'Kapitoly', ps_wealth:'💎 Jmění',
    appearance:'🎨 Vzhled', lang_ui:'🌐 Jazyk rozhraní',
    btn_change_lang:'🌍 Změnit jazyk', btn_logout:'🚪 Odhlásit se',
    qr_title:'📱 Sdílet tuto kapitolu', btn_qr_copy:'📋 Kopírovat', btn_close:'Zavřít',
    langmodal_title:'Změnit jazyk', lm_speak:'Mluvím:', lm_learn:'Chci se naučit:',
    btn_apply:'Použít', btn_cancel:'Zrušit',
    amod_market:'Skutečná tržní cena', amod_position:'Tvá pozice',
    amod_units:'Vlastněné jednotky', amod_value:'Aktuální hodnota',
    amod_daily:'Dividendy / den', amod_pv:'Kapitálový zisk',
    btn_buy:'Koupit', btn_sell:'Prodat',
    joined:'Člen od ',
  },
};
